apiVersion: v1 
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql  #mysql component service 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1.0
        volumeMounts:
        - name: nginx.conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx.conf
        configMap:
          name: frontend
          items:
            - key: nginx.conf
              path: nginx.conf
---

apiVersion: v1 
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    

        
    